services:
  - type: web
    name: crosshairlab-admin-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: PORT
        value: 8000
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "False"
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
        sync: false
      - key: RECAPTCHA_SECRET_KEY
        sync: false
      - key: ADMIN_WHITELIST_IPS
        sync: false
      - key: REDIS_URL
        sync: false
    healthCheckPath: /health 
