services:
  # API service
  - type: web
    name: crosshairlab-api
    runtime: python
    plan: free
    rootDirectory: api.crosshairlab.app
    buildCommand: pip install -r requirements.txt
    startCommand: cd api && python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: PORT
        value: 8000
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "False"
      - key: ADMIN_SECRET_PATH
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true
